spring:
  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: 500

---
spring:
  config:
    activate:
      on-profile: database-local
  datasource:
    url: "jdbc:postgresql://postgresql:5432/postgres"
    username: "postgres"
    password: "postgres"
  sql:
    init:
      platform: postgresql
      mode: always

decorator:
  datasource:
    enabled: true

---
spring:
  config:
    activate:
      on-profile: database-dev
  datasource:
    url: "{cipher}e34cf29eacad199dd1ae72a4b6025c102a7d394a0ab3ff1ebcba0f9ff6a4d0f657903627386bab8f5a56379d162975cd136e7af25e6948f6643496555357114c"
    username: "{cipher}1156c6e31c9aca5dcd0a28d5738acb16563d8195e96d0ed7b5f2c5c8ac58a1a8"
    password: "{cipher}1156c6e31c9aca5dcd0a28d5738acb16563d8195e96d0ed7b5f2c5c8ac58a1a8"
  sql:
    init:
      platform: postgresql
      mode: always

decorator:
  datasource:
    enabled: true

---
spring:
  config:
    activate:
      on-profile: database-prod
  datasource:
    url: "{cipher}452e01908f8727db74432e630a30200be4339ce0d673c61454e4c342313159baa7b1023596a0d526e480fd5894a8337d9de913b396b1e216f354f8b8db9bed55"
    username: "{cipher}ae77ff5605a5e204b5e0d448c2616f03e0a6d85a902c4585df6f9a3ec374dcba"
    password: "{cipher}8b09d8723d1f354950fd9f0594784ad72d38471e036283e3189fb46872da8859"
  sql:
    init:
      platform: postgresql
      mode: always
    