# https://docs.spring.io/spring-boot/docs/3.0.0/reference/html/web.html#web.graphql
---
spring:
  config:
    activate:
      on-profile: graphql-local, graphql-dev
  graphql:
    graphiql:
      enabled: true
    schema:
      printer:
        enabled: true
    cors:
      allowed-origins: "*"
      allowed-methods: "*"
      max-age: 1800s

---
spring:
  config:
    activate:
      on-profile: graphql-prod
  graphql:
    graphiql:
      enabled: true
    schema:
      printer:
        enabled: true
    cors:
      allowed-origins: "*"
      allowed-methods: GET,POST
      max-age: 1800s      