management:
  endpoints:
    # enabled-by-default: false
    # jmx:
    #   exposure:
    #     exclude: "*"
    web:
      exposure:
        # exclude: "*"
        include: "info,health,refresh,metrics,prometheus"
  # endpoint:
  #   health:
  #     enabled: true
  #   info:
  #     enabled: true
  #   metrics:
  #     enabled: true
  #   prometheus:
  #     enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  # server:
  #   port: 9999
