---
spring:
  config:
    activate:
      on-profile: opensearch-local
opensearch:
  uris: ${OPENSEARCH_URIS:https://dev.localhost:9200,http://dev.localhost:9200}
#  username: ${OPENSEARCH_USER}
#  password: ${OPENSEARCH_PASS}


---
spring:
  config:
    activate:
      on-profile: opensearch-dev
opensearch:
  uris: ${OPENSEARCH_URIS:https://mdtp.gaia3d.com:9200}
#  username: ${OPENSEARCH_USER}
#  password: ${OPENSEARCH_PASS}

---
spring:
  config:
    activate:
      on-profile: opensearch-prod
opensearch:
  uris: ${OPENSEARCH_URIS:http://opensearch-node:9200}
