---
spring:
  config:
    activate:
      on-profile: security-local
  security:
    oauth2:
      resource-server:
        jwt:
          jwk-set-uri: "http://keycloak:8080/auth/realms/mago3d/protocol/openid-connect/certs"

logging:
  level:
    org.springframework.security.web.csrf: debug

mago3d:
  userset:
    endpoint: http://userset:8080/app/api/userset/graphql
---
spring:
  config:
    activate:
      on-profile: security-dev
  security:
    oauth2:
      resource-server:
        jwt:
          jwk-set-uri: "{cipher}7926b434ec1456074665b7c5f6147e69ecbbce6c2d59dab4ecb3ae23e134259ea0c98c133679502cba4ecfd971856c8258872f892df357cd6fbe196e1ab19699c47458ac867dac8c189df7ef759e543aed16e12743f1c89dc8a7cddb986f210f"

logging:
  level:
    org.springframework.security.web.csrf: debug

mago3d:
  userset:
    endpoint: https://map.gaia3d.com/app/api/userset/graphql
---
spring:
  config:
    activate:
      on-profile: security-prod
  security:
    oauth2:
      resource-server:
        jwt:
          jwk-set-uri: "{cipher}d3c7e6a77fa4b456d09a2712da545c03f2f90e53785ffb6edc4ab1e25b7987eec2a2791ee669b861c966400e5f252c6a42912853649b7cdda2a8b90b8055e31987b6d195a337eca15679f4f98ff1f9ce4c22df4e36f3813b002206221bba5c1c"

mago3d:
  userset:
    endpoint: http://userset:8080/app/api/userset/graphql