---
spring:
  config:
    activate:
      on-profile: storage-local
  cloud:
    aws:
      credentials:
        access-key: "{cipher}56e407baff3320a0293c4259bb91409e566bdba0a364fe3356e04a5d7e1f3d38"
        secret-key: "{cipher}cef47f4fbac8109e5046ce4429a20ad7f4a655de42df4c7c80804a60eb8f69fc"
      region:
        static: ap-northeast-2
      s3:
        endpoint: http://dev.localhost:9000
        path-style-access-enabled: true
        region: "ap-northeast-2"
        bucket: "mdtp"

---
spring:
  config:
    activate:
      on-profile: storage-dev
  cloud:
    aws:
      credentials:
        access-key: "{cipher}56e407baff3320a0293c4259bb91409e566bdba0a364fe3356e04a5d7e1f3d38"
        secret-key: "{cipher}cef47f4fbac8109e5046ce4429a20ad7f4a655de42df4c7c80804a60eb8f69fc"
      region:
        static: ap-northeast-2
      s3:
        endpoint: http://map.gaia3d.com:9000
        path-style-access-enabled: true
        region: "ap-northeast-2"
        bucket: "mdtp"

---
spring:
  config:
    activate:
      on-profile: storage-prod
  cloud:
    aws:
      credentials:
        access-key: "{cipher}14e510378298bcc254eff20b8da97e08392c77a7a4e2e77a17c68f25b73dbf74"
        secret-key: "{cipher}b0df22e98ad682dd8b9127725f940d09580c40875882a3542cce225885c657ad"
      region:
        static: ap-northeast-2
      s3:
        endpoint: http://map.gaia3d.com:9000
        path-style-access-enabled: true
        region: "ap-northeast-2"
        bucket: "mdtp"
        