version: "3.9"

name: mago3d-apps

x-env: &env
  SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}

services:
  gdal-converter:
    environment:
      <<: *env

  f4d-converter:
    environment:
      <<: *env

  t3d-converter:
    environment:
      <<: *env

  terrain-converter:
    environment:
      <<: *env

  dataset:
    environment:
      <<: *env
      SERVER_SERVLET_CONTEXT_PATH: /app/api/dataset
    labels:
      - traefik.enable=true
      - traefik.http.routers.dataset.rule=Host(`${DOMAIN}`) && PathPrefix(`/app/api/dataset`)
      - traefik.http.routers.dataset.entrypoints=websecure
      - traefik.http.routers.dataset.tls=true
      - traefik.http.routers.dataset.service=dataset
      - traefik.http.services.dataset.loadbalancer.server.port=8080

  userset:
    environment:
      <<: *env
      SERVER_SERVLET_CONTEXT_PATH: /app/api/userset
    labels:
      - traefik.enable=true
      - traefik.http.routers.userset.rule=Host(`${DOMAIN}`) && PathPrefix(`/app/api/userset`)
      - traefik.http.routers.userset.entrypoints=websecure
      - traefik.http.routers.userset.tls=true
      - traefik.http.routers.userset.service=userset
      - traefik.http.services.userset.loadbalancer.server.port=8080

  layerset:
    environment:
      <<: *env
      SERVER_SERVLET_CONTEXT_PATH: /app/api/layerset
    labels:
      - traefik.enable=true
      - traefik.http.routers.layerset.rule=Host(`${DOMAIN}`) && PathPrefix(`/app/api/layerset`)
      - traefik.http.routers.layerset.entrypoints=websecure
      - traefik.http.routers.layerset.tls=true
      - traefik.http.routers.layerset.service=layerset
      - traefik.http.services.layerset.loadbalancer.server.port=8080