version: "3.9"

networks:
  mago3d:
    external: true

x-networks: &networks
  mago3d:

x-logging-fluentd: &logging-fluentd
  fluentd-address: localhost:24224
  fluentd-async: "true"
  fluentd-buffer-limit: 0
  tag: docker.springboot.{{.Name}}

services:
  gdal-converter:
    image: ${REGISTRY}/mdtp-gdal-converter:latest
    networks: *networks
    logging:
      driver: fluentd
      options:
        <<: *logging-fluentd
        tag: docker.springboot.gdal-converter

  t3d-converter:
    image: ${REGISTRY}/mdtp-t3d-converter:latest
    networks: *networks
    logging:
      driver: fluentd
      options:
        <<: *logging-fluentd
        tag: docker.springboot.t3d-converter

  f4d-converter:
    image: ${REGISTRY}/mdtp-f4d-converter:latest
    networks: *networks
    logging:
      driver: fluentd
      options:
        <<: *logging-fluentd
        tag: docker.springboot.f4d-converter

  terrain-converter:
    image: ${REGISTRY}/mdtp-terrain-converter:latest
    networks: *networks
    logging:
      driver: fluentd
      options:
        <<: *logging-fluentd
        tag: docker.springboot.terrain-converter

  dataset:
    image: ${REGISTRY}/mdtp-dataset-app:latest
    networks: *networks
    logging:
      driver: fluentd
      options:
        <<: *logging-fluentd
        tag: docker.springboot.dataset

  userset:
    image: ${REGISTRY}/mdtp-userset-app:latest
    networks: *networks
    logging:
      driver: fluentd
      options:
        <<: *logging-fluentd
        tag: docker.springboot.userset

  layerset:
    image: ${REGISTRY}/mdtp-layerset-app:latest
    networks: *networks
    logging:
      driver: fluentd
      options:
        <<: *logging-fluentd
        tag: docker.springboot.layerset