version: "3.9"

networks:
  mago3d:
    external: true

x-networks: &networks
  mago3d:

services:
  apidoc:
    image: ${REGISTRY}/mago3d-api-doc:latest
    networks: *networks
    deploy:
      replicas: 1

  frontend:
    image: ${REGISTRY}/mago3d-frontend:latest
    networks: *networks
    deploy:
      replicas: 1