version: "3.9"

name: mago3d-front

services:
  apidoc:
    labels:
      - traefik.enable=true
      - traefik.http.routers.apidoc.rule=Host(`${DOMAIN}`) && PathPrefix(`/doc`)
      - traefik.http.routers.apidoc.entrypoints=websecure
      - traefik.http.routers.apidoc.service=apidoc
      - traefik.http.services.apidoc.loadbalancer.server.port=80

  frontend:
    labels:
      - traefik.enable=true
      - traefik.http.routers.frontend.rule=Host(`${DOMAIN}`) && (PathPrefix(`/user`) || PathPrefix(`/admin`))
      - traefik.http.routers.frontend.entrypoints=websecure
      - traefik.http.routers.frontend.service=frontend
      - traefik.http.services.frontend.loadbalancer.server.port=80