server:
  shutdown: graceful
  servlet:
    context-path: /app/api/dataset
    encoding:
      charset: utf-8
      force: true
  tomcat:
    max-swallow-size: -1
    max-http-form-post-size: -1
  forward-headers-strategy: framework
  
spring:
  config:
    import:
      - import/database.yml
      - import/graphql.yml      
      - import/rabbitmq.yml
      - import/security.yml
      - import/storage.yml
  servlet:
    multipart:
      max-file-size: 2GB
      max-request-size: 2GB

  #  cache:
  #    type: none

  cloud:
    function:
      definition: f4dConsumer;t3dConsumer;gdalConsumer;terrainConsumer
    stream:
      bindings:
        # F4D
        f4dProducer-out-0:
          destination: dataflow.tx.f4d.req
        f4dConsumer-in-0:
          destination: dataflow.tx.f4d.res
          group: dataset

        # 3dTiles
        t3dProducer-out-0:
          destination: dataflow.tx.t3d.req
        t3dConsumer-in-0:
          destination: dataflow.tx.t3d.res
          group: dataset

        # GDAL
        gdalProducer-out-0:
          destination: dataflow.tx.gdal.req
        gdalConsumer-in-0:
          destination: dataflow.tx.gdal.res
          group: dataset

        # Terrain
        terrainProducer-out-0:
          destination: dataflow.tx.terrain.req
        terrainConsumer-in-0:
          destination: dataflow.tx.terrain.res
          group: dataset

management:
  endpoints:
    web:
      exposure:
        include: "health,refresh,prometheus"
  metrics:
    tags:
      application: ${spring.application.name}
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true          