server:
  shutdown: graceful

spring:
  config:
    import:
      - import/rabbitmq.yml
      - import/storage.yml 
  profiles:
    group:
      dev:
        - logging-json
      prod:
        - logging-json

  cloud:
    function:
      definition: requestConsumer
    stream:
      bindings:
        requestConsumer-in-0:
          destination: ${EXCHANGE_NAME:dataflow.tx.gdal.req}  # Topic Exchange
          group: ${GROUP_NAME:gdal-converter}
        responseProducer-out-0:
          destination: ${EXCHANGE_NAME:dataflow.tx.gdal.res}  # Topic Exchange
