server:
  shutdown: graceful

spring:
  config:
    import:
      - import/rabbitmq.yml
      - import/storage.yml 
      - import/management.yml
  profiles:
    group:
      dev:
        - logging-json
      prod:
        - logging-json

  cloud:
    function:
      definition: convertConsumer
    stream:
      bindings:
        convertConsumer-in-0:
          destination: ${EXCHANGE_NAME:dataflow.tx.t3d.req}  # Topic Exchange
          group: ${GROUP_NAME:tiles3d-converter}
        convertProducer-out-0:
          destination: ${EXCHANGE_NAME:dataflow.tx.t3d.res}  # Topic Exchange