server:
  shutdown: graceful
  servlet:
    context-path: /app/api/userset
    encoding:
      charset: utf-8
      force: true

spring:
  config:
    import:
      - import/database.yml
      - import/graphql.yml      
      - import/security.yml
  graphql:
    schema:
      locations: classpath:graphql-comm, classpath:graphql-userset

keycloak-client:
  url: http://keycloak:8080/auth
  realm: mago3d
  client-id: mago3d-api
  client-secret: UdYVSHNfwjJP1bkdOi2k7mMBBMTBRzUL

management:
  endpoints:
    web:
      exposure:
        include: "health,refresh,prometheus"
  metrics:
    tags:
      application: ${spring.application.name}
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true